package com.example;

import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.cloud.contract.stubrunner.StubFinder;
import org.springframework.cloud.contract.stubrunner.spring.AutoConfigureStubRunner;
import org.springframework.cloud.contract.stubrunner.spring.StubRunnerProperties;
import org.springframework.http.MediaType;
import org.springframework.http.RequestEntity;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.RestTemplate;

import java.net.URI;

import static org.assertj.core.api.BDDAssertions.then;

/**
 * Demonstrates that Spring Cloud Contract's stub runner can consume stubs
 * generated by Stubborn Contract.
 *
 * The producer (compat-stubborn-producer) was built with Stubborn Contract.
 * Its stubs are in the local Maven repo. This test loads them via SCC's
 * AutoConfigureStubRunner — proving WireMock stub format compatibility.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
@AutoConfigureStubRunner(
    ids = "com.example:compat-stubborn-producer:+:stubs",
    stubsMode = StubRunnerProperties.StubsMode.LOCAL
)
class StubbornStubsFromSccRunnerTest {

    @Autowired
    StubFinder stubFinder;

    @Test
    void scc_stub_runner_can_serve_stubborn_generated_stubs() {
        int port = stubFinder.findStubUrl("com.example", "compat-stubborn-producer").getPort();

        ResponseEntity<String> response = new RestTemplate().exchange(
            RequestEntity.post(URI.create("http://localhost:" + port + "/check"))
                .contentType(MediaType.APPLICATION_JSON)
                .body("{\"age\":22}"),
            String.class
        );

        then(response.getStatusCode().value()).isEqualTo(200);
        then(response.getBody()).isEqualTo("OK");
    }
}
