package com.example;

import org.junit.jupiter.api.Test;

import sh.stubborn.contract.stubrunner.StubFinder;
import sh.stubborn.contract.stubrunner.spring.AutoConfigureStubRunner;
import sh.stubborn.contract.stubrunner.StubsMode;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.http.RequestEntity;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.RestTemplate;

import java.net.URI;

import static org.assertj.core.api.BDDAssertions.then;

/**
 * Demonstrates that Stubborn Contract's stub runner can consume stubs
 * generated by Spring Cloud Contract (SCC).
 *
 * The producer (compat-scc-producer) was built with SCC 4.x. Its stubs
 * are in the local Maven repo. This test loads them via Stubborn's
 * AutoConfigureStubRunner — proving WireMock stub format compatibility.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
@AutoConfigureStubRunner(
    ids = "com.example:compat-scc-producer:+:stubs",
    stubsMode = StubsMode.LOCAL
)
class SccStubsFromStubbornRunnerTest {

    @Autowired
    StubFinder stubFinder;

    @Test
    void stubborn_stub_runner_can_serve_scc_generated_stubs() {
        int port = stubFinder.findStubUrl("com.example", "compat-scc-producer").getPort();

        ResponseEntity<String> response = new RestTemplate().exchange(
            RequestEntity.post(URI.create("http://localhost:" + port + "/check"))
                .contentType(MediaType.APPLICATION_JSON)
                .body("{\"age\":22}"),
            String.class
        );

        then(response.getStatusCode().value()).isEqualTo(200);
        then(response.getBody()).isEqualTo("OK");
    }
}
